### ISSUE TITLE
Check files

### ISSUE THREAD

**Issue by cathblatter** [INS-Basel/fidelitysim#1]
I set the package structure up and added the code, currently `devtools::check()` gives me 3 warnings and 1 note, 
@trutscheld - please check&modify the following files: 

- [x] DESCRIPTION: Especially 'Title' and 'Description'
- [x] README: does it make sense what I wrote? Modify README.Rmd, then Cmd+Shift+K to re-knit the README.md file (do not modify README.md) 
- [x]  All code files in R/ -> I added roxygen skeletons to all functions but please describe all values and outputs given.

You can run `devtools::check()` from time to time to see how many/what warnings persist.

Once all is done and you commit and push all changes to github, an automatic R cmd check will happen through GitHub Actions and notify me about anything. 

Please ask back if you there are questions

**Comment by trutscheld** [comment]
devtools check is ok now at my PC.

It is necessary to push also all .Rd files????
Ok. I pushed aslo because of check on gitHub failed. Maybe now....
Nop. No clue why it doesn't work here on gitHub....

**Comment by trutscheld** [comment]
I suggest to look into pacakage SamplingCRT and improve. For example:

include some of the function in fidelitysim  into, because of better fit
- [ ] implementMatrix.parallele "cross-over"
- [ ] implementMatrix.crossover

designMatrix in Package has 3 types, but "cross-sectional" is maybe false and has to be 'cross-over'

I am pretty sure now that the corresponfing gitHub Project of the package is "[samplingData](https://github.com/trutscheld/samplingData)" because in Description the name is "samplingDataCRT" and latest version 2017-01-20, but released on CRAN in February 2017.

I think we can work with that...

**Comment by cathblatter** [comment]
to your first comment -> I reformatted the Description-file in 00619cb , the check is now fine, 
I look at the other stuff tomorrow
